### ISSUE TITLE
What's the best conference talk you've given and the best you've seen?

### ISSUE THREAD

**Issue by loz** [r00k/AMA#1]

**Comment by r00k** [comment]
I think the first two talks on here are my best: http://www.benorenstein.com/talks/

Rich Hickey's "Simple Made Easy" probably changed my thinking more than any other: http://www.infoq.com/presentations/Simple-Made-Easy.

Russ Olsen's "To The Moon" is my favorite example of engaging storytelling: https://www.youtube.com/watch?v=4Sso4HtvJsw

Another favorite is the well-known talk Ben Zander did at TED: http://www.ted.com/talks/benjamin_zander_on_music_and_passion

**Comment by cadizjavier** [comment]
For me is "Refactoring from Good to Great". I have seen it several times and always learn something new.

**Comment by r00k** [comment]
Glad you liked it!

As I mentioned above, that's in my top two for sure.

**Comment by srigi** [comment]
"Refactoring from Good to Great" is my favorite too. And right after that "MIT professor prank" from "How to Talk to Developers" :)
