### ISSUE TITLE
Advice for two 21-year-olds who want to mix world travel and working remotely?

### ISSUE THREAD

**Issue by indiesquidge** [r00k/AMA#10]
I'm not sure if you remember me personally, but I was at the Turing School while you were there in January. It was awesome having you there. Here's my 2015 goal:

My friend and I want to gather US clients and go work remotely while traveling Europe. He is a self-taught designer who has been supporting himself on the work he does through Techstars and random, one-off jobs. I am a Turing student, junior developer, with high ambitions and low experience.

When I get out of Turing at the end of June, I want to get a few actual consultancy jobs under my belt before I try and travel anywhere. Clients aren't the biggest issue on my plate right now, since a lot of people in my network have been more than generous in passing off small jobs to me. We plan on gathering clients in the US so that we don't have to worry about foreign work visas or taxes.
**What I'm most scared of is jumping from junior developer at a bootcamp to essentially running my own remote consultancy.**

Obviously we would be transparent about our naivety and inexperience to all potential clients, and counter that by charging lower prices than a bigger firm would. We aren't doing this for the money, we are doing it for the experience of working remotely and enjoying travel at the same time.

This is getting long winded, so thanks for even reading this far. Tl;dr:
#### _What advice do you have for my friend and I while we embark across Europe while maintaining remote jobs in America?_

I am not asking you if it's a good idea to try and do this, because it's going to happen regardless of what anyone tells us. It scares me, and that's exactly why I think it needs to be put into action. The way I see it, as two 21-year-olds, we have the lowest number of dependencies and consequences that we ever will in our lives, so why not take risks.

**Comment by r00k** [comment]
Brennan Dunn writes incredible stuff about freelancing: http://doubleyourfreelancing.com/. Go read a bunch of that.

> Obviously we would be transparent about our naivety and inexperience to all potential clients, and counter that by charging lower prices than a bigger firm would.

I think Brennan would tell you not to emphasize this. Focus on how you're going to solve their problems, then do so.

> It scares me, and that's exactly why I think it needs to be put into action.

Totally agree. Keep up this habit.

I don't have much advice for what to do given that you'll be remote, but know that you're going to have to be an incredible communicator.

**Comment by indiesquidge** [comment]
Thanks a lot :)

**Comment by r00k** [comment]
Also, I totally remember you, Austin. :)
