### ISSUE TITLE
What is your take on Elixir ?

### ISSUE THREAD

**Issue by cadizjavier** [r00k/AMA#11]
As a prominent Ruby/Rails developer and your recent take on functional programming with Clojure, what do you think about Elixir and about the Phoenix framework ?

**Comment by r00k** [comment]
Haven't spent nearly enough time with it to form an opinion, I'm afraid.

I've heard Erlang's OTP is wonderful, which is intriguing.

**Comment by cadizjavier** [comment]
Well if you feel inspired sometime i would like to see an opinion from you about Elixir/Phoenix. For my point of view it seems a to follow platform, very friendly for a Ruby background developer, very robust in terms of fault tolerance and with an outstanding response speed. 

I will like to share with you two resources that help me to got some perspective about it:
- https://medium.com/@kenmazaika/why-im-betting-on-elixir-7c8f847b58
- http://phoenix.thefirehoseproject.com/

**Comment by r00k** [comment]
Thanks for the links!

On Sat, Mar 14, 2015 at 10:35 PM, Javier Cadiz notifications@github.com
wrote:

> Well if you feel inspired sometime i would like to see an opinion from you
> about Elixir/Phoenix. For my point of view it seems a to follow platform,
> very friendly for a Ruby background developer, very robust in terms of
> fault tolerance and with an outstanding response speed.
> 
> I will like to share with you two resources that help me to got some
> perspective about it:
> - https://medium.com/@kenmazaika/why-im-betting-on-elixir-7c8f847b58
> - http://phoenix.thefirehoseproject.com/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/r00k/AMA/issues/11#issuecomment-80745012.

## 

-Ben
