### ISSUE TITLE
What do you think about being a full-stack developer ?

### ISSUE THREAD

**Issue by cadizjavier** [r00k/AMA#12]
I found myself digging a lot into the hole stack, front the frontend with heavy JS to the backend using Laravel at first then Rails. I like a lot the mobile development too and do iOS development almost every day, recently i'm exploring the Android platform too. Some times get very excited about new tech and want to try with those too.
Did you think that is a healthy approach ? I'm kinda afraid that doing that way i will be wasting tons of time with all the languages and platforms and not enough time learning key skills like Data Structures, Design Patterns, TDD. 
Other than that, is hard to focus in one platform these days, the hole stack has never been so big and most of the time you need to know bunch of stuffs to get something done. Is exciting and scaring at the same time.
What did you think about it and your advice to a young programmer like me.

**Comment by r00k** [comment]
I think it's a good idea to learn a broad selection of skills, but only after you acquire deep experience in one or two. 

Are you actually shipping things in Rails _and_ JS _and _Android? Finishing an idea and putting it out in the world?

If not, focus. Pick one technology and ship something substantial.

**Comment by cadizjavier** [comment]
Yes, but mostly as a freelance developer, that's why i need to move into a broad selection of skills. But yes, understand your point and at the end i doesn't matter the specific technology of choice as long as the product solves a problem and gets shipped.
