### ISSUE TITLE
What's a non-software book that has helped you the most in writing better software?

### ISSUE THREAD

**Issue by swanson** [r00k/AMA#14]

**Comment by r00k** [comment]
Nothing is coming to mind, so I'll leave this open for a bit and come back to it.

**Comment by r00k** [comment]
Two books come to mind:
- [The Passionate Programmer](http://www.amazon.com/gp/product/1934356344/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=1934356344&linkCode=as2&tag=codeulate-20&linkId=OL4EAFOMYVGO2ZDF) (Kind of a prorgramming book, but it's non-technical.)
- [How to Fail at Almost Everything and Still Win Big](http://www.amazon.com/gp/product/1591847745/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=1591847745&linkCode=as2&tag=codeulate-20&linkId=VJ6JSDON3QHSB2SX)

Both are excellent.

**Comment by queuebit** [comment]
@sivers [book list](http://sivers.org/book) is a great place to go for book recommendations.

Start with the 10/10 books, skim through his notes to give yourself an idea of the topic and whether it would be a good book for you.

I learned a lot from http://sivers.org/book/SoGood and http://sivers.org/book/PersonalMBA.
