### ISSUE TITLE
If you had another month at Turing School, what would you focus on / want to accomplish?

### ISSUE THREAD

**Issue by wolovim** [r00k/AMA#15]

**Comment by r00k** [comment]
I'd want to split a cohort in half.

50% do the standard first module introducing Ruby.
50% learn Scheme and read How to Design Programs. The last week of the module we introduce Ruby and cover the differences.

I have a hypothesis that Ruby is a bad first language, and pure beginners would benefit from a different introduction. I think they'd come out as better programmers at the end, even with less total Ruby experience.

This experiment give clues as to whether I'm right.
