### ISSUE TITLE
Books and Videos

### ISSUE THREAD

**Issue by arbaaz** [r00k/AMA#16]
I would call myself  Intermediate programmer and Rubyist. Which resource you recommend to become more awesome.

**Comment by r00k** [comment]
- http://upcase.com
- [Clean Code by Bob Martin](http://www.amazon.com/gp/product/0132350882/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=0132350882&linkCode=as2&tag=codeulate-20&linkId=CTSQSLWQVCHR35FI)
- Destroy All Software screencasts.
