### ISSUE TITLE
Your future in Functional programming.

### ISSUE THREAD

**Issue by skippednote** [r00k/AMA#18]
Now that you have dipped your toes in both Clojure/ClojureScript and Haskell, how do you think both of them fair when it comes to web development or building small cli apps like the zsh_history parse you had built. Also will you be sticking to one of either? 

I really like Clojure for its Lisp background but I'm a bit confused  and would really appreciate some advice on how to get efficient at it.

**Comment by r00k** [comment]
> Now that you have dipped your toes in both Clojure/ClojureScript and Haskell, how do you think both of them fair when it comes to web development or building small cli apps like the zsh_history parse you had built.

They both seem like extremely well-designed languages and good at a variety of tasks.

> Also will you be sticking to one of either?

I think it's likely that there is some Haskell in my near future.

> I really like Clojure for its Lisp background but I'm a bit confused and would really appreciate some advice on how to get efficient at it.

Ideally, go work somewhere with good Clojure programmers. Write a lot of it. Get feedback on what you wrote.

**Comment by skippednote** [comment]
Thanks Ben, much appreciated!
