### ISSUE TITLE
Prep Food

### ISSUE THREAD

**Issue by cstadach** [r00k/AMA#19]
What do you consider good food to prepare you for a day of coding?

**Comment by r00k** [comment]
Interesting question!

I like my breakfast on all days to be a ton of protein, some good veggies, and not many carbs.

Most days I'll make a 3-egg scramble with onions and spinach with a few strips of bacon.

**Comment by steverob** [comment]
Nice :)

**Comment by cstadach** [comment]
That sounds like a really good breakfast.

I am currently trying to find out which foods get me into the right state of mind to code and not sleepy or moody.

Nothing is worse than coding on a growling or overflown stomac and the quality of the code written under those circumstances is bad as well from my point of view.
