### ISSUE TITLE
Were you intimidated by vim before you got into it?

### ISSUE THREAD

**Issue by steverob** [r00k/AMA#20]
Learning vim seems so hard. Did you feel the same before you started out? :)

**Comment by r00k** [comment]
I don't remember being intimidated by it. 

However, I have good news! 

https://robots.thoughtbot.com/the-vim-learning-curve-is-a-myth

**Comment by steverob** [comment]
Thanks! :) I know there's no reason to be scared about. Still.

 Will keep working on it. :sparkle:

**Comment by maxcodes** [comment]
I just recently switched to Vim less than two months ago (thanks to Giant Robots, mostly). What had held me back in the past was the notion of the learning curve. Can cofirm that it is a myth. You get up to speed in less than a week. Just google a lot in the beginning and keep a cheat sheet.
