### ISSUE TITLE
Introducing change in the company you work for

### ISSUE THREAD

**Issue by cloud8421** [r00k/AMA#22]
Hi,

I've asked you this question in person at BathRuby two days ago, but it may be useful for other people as well so I'll repost it here.

How do you approach introducing change in a company whose expertise is mainly in one/two languages and framework? In my case it means trying some Erlang/Elixir and Clojure in a 100% Ruby/Javascript shop.

**Comment by r00k** [comment]
Bit by bit, with lots of different approaches.

Lots of good specifics on how we're introducing Haskell to thoughtbot here: http://giantrobots.fm/137.
