### ISSUE TITLE
To open source or not to open source

### ISSUE THREAD

**Issue by firstrow** [r00k/AMA#28]
Hello. At this moment i'm writing tool to collect, store and search big amount of logs in real-time(like logstash, for example).
It is my free-time project. At the beginning I thought that I will it run as SaaS, than I realized, such approach need a lot of money to pay for the servers. And I've decided to setup and run on clients servers.
And all this time I'm thinking about open-sourcing this project.
I know, there is a lot of articles on the internet, but I need advice from someone from community.

So, my question is: What can I take back from open-sourcing, how valuable can it be to me?

Thank you.

**Comment by r00k** [comment]
Hi!

It's hard to say if open sourcing your project will get you much benefit. The most likely scenario is that you open-source it and nothing changes. 

If you happen to get people using it who have development skills, it's possible that you may get some community contributions. It's also possible that your clients will like that your code is open source, so it may help you close deals.
