### ISSUE TITLE
If you were to create a programming language, what would it be like?

### ISSUE THREAD

**Issue by clemensg** [r00k/AMA#29]
(And would it have a type system?)

**Comment by r00k** [comment]
It would likely be 30% complete and never released :).

But if I'm just going to wave my hands: I'd like to see Haskell's type system jammed into Clojure's syntax but whitespace sensitive.

**Comment by andrewhr** [comment]
When you say whitespace sensitive do you say `(whitespace (instead (of (parentheses)))))`?

**Comment by philipcunningham** [comment]
> Haskell's type system jammed into Clojure's syntax but whitespace sensitive.

Pure dreamboats.
