### ISSUE TITLE
Other repositories like Upcase and Trailmix?

### ISSUE THREAD

**Issue by prbroadfoot** [r00k/AMA#30]
I've gotten a huge amount of value from studying these two Rails apps. They are very well-designed and cleanly written, and I look at them for inspiration as I write my own apps :-)

Wondering if you know of anything else similar.

**Comment by r00k** [comment]
I'm glad to hear they were useful!

Unfortunately, no similar repos are coming to mind. Maybe other folks that see this thread can chime in.

**Comment by prbroadfoot** [comment]
Thanks anyway!

My opinion in case you're interested: If I had to choose between access to 10 future Weekly Iteration videos or access to the source code of another Rails app made by thoughtbot developers, I would choose the Rails app.

**Comment by jsteiner** [comment]
@broadfootp check out https://github.com/thoughtbot/hound

**Comment by eliotsykes** [comment]
@prbroadfoot you might like https://github.com/eliotsykes/real-world-rails, a curated collection of open-sourced Rails apps including hound and trailmix
