### ISSUE TITLE
What tools do you use in creating the Giant Robots podcast?

### ISSUE THREAD

**Issue by nickbytes** [r00k/AMA#31]
What tools do you use for production and editing?

It seems like sometimes you interview people who are remote, I'm interested to see hear about how you do this as well.

Also, really enjoy the podcast, good work.

**Comment by r00k** [comment]
@thoughtbotthom Any chance you'd be willing to share some details?

**Comment by r00k** [comment]
Gonna close this for now, but also pinging @thoughtbotthom in case he has some time.
