### ISSUE TITLE
RSI

### ISSUE THREAD

**Issue by ianks** [r00k/AMA#34]
I noticed you mentioned you had a bout of RSI in one of your videos. How has that been since then?

I recently have been having pinky pains (from Enter and Ctrl) that extend down the arm. This is a very recent development.

Here has been line line of action so far:
- Bought a Truly Ergonomic Keyboard
- Created mappings the minimize any stretch of the pinkies
- I am taking a week off from all typing
- Think hard about not allowing myself to type on my laptop (the MacBook keyboard is brutal for me)

I know you are not a doctor, but I just wanted your experience with this as a programmer. Are there any stretches you do? Is there anything you would add to this list? Is 1 week enough time to break? 

Thanks in advance!

**Comment by r00k** [comment]
I had the same thing you are experiencing. Been fine for a few years now though.

This keyboard eliminated the pinkie reach entirely: https://www.kinesis-ergo.com/shop/advantage-for-pc-mac/

I think that made the biggest difference.

I also did some fairly standard stretches of my forearms that may have helped. Not sure.

No idea if one week is enough for you. I'd recommend seeing an occupational therapist. They specialize in this sort of thing.

**Comment by DavsX** [comment]
Check out this video: https://www.youtube.com/watch?v=-hlWgH3_0NU
I used to do these stretches as part of my climbing 'routine'.
