### ISSUE TITLE
Advice for aspiring self-taught developers?

### ISSUE THREAD

**Issue by sungwoncho** [r00k/AMA#35]
Hi Ben. I watched some of your talks on YouTube as per my colleague's recommendation. I think they were immensely helpful. That's why I want to ask you if you have any advice for people in my shoes.

I am fresh out of college and working as a Rails dev intern. I don't have a technical background, and have been teaching myself Ruby for a little less than a year. I want to be the best developer I can be. Are there some common hurdles that self-taught developers face, and do you have any advice to give me?

**Comment by r00k** [comment]
We made https://upcase.com precisely for people like you.
