### ISSUE TITLE
Goals.

### ISSUE THREAD

**Issue by cjavdev** [r00k/AMA#36]
Thinking personal and professional, 1 year, 5 year, 10 year. Do you set them? Willing to share any?

**Comment by r00k** [comment]
I don't set long-term goals very often. I almost certainly should.

Past professional goals have been to get hired at thoughtbot and to give a keynote, both done.

Current personal goal is to win my first boxing match (coming up on 5/13).

**Comment by cjavdev** [comment]
Whoa! winning a boxing match sounds intense. What a great test of character :)

**Comment by r00k** [comment]
I suspect losing one is even more intense, but hope to not learn first-hand.
