### ISSUE TITLE
At thoughtbot, does Investment Time come with any profit-sharing/bonus if the project generates revenue?

### ISSUE THREAD

**Issue by swanson** [r00k/AMA#38]
Easy example: I write a book during Investment Time, does the money from sales go to thoughtbot? myself? some split?

**Comment by queuebit** [comment]
I had wondered the same with your books, like https://robots.thoughtbot.com/maybe-haskell-our-newest-book.

**Comment by r00k** [comment]
I actually don't know. I'd guess there isn't a split, since authors are being paid their salary while writing.

@calebthompson runs that program. Maybe he'll weigh in.

**Comment by calebhearth** [comment]
As far as I know authors don't get a revenue split.

**Comment by r00k** [comment]
I think in general, investment activities don't tend to generate that much income, so there's not much revenue to split.

However, I've found the partners to be reasonable about setting up commission/revenue-sharing for things that become successful. Upcase, for instance.

**Comment by swanson** [comment]
That's what I figured - thanks for the insight :)
