### ISSUE TITLE
What has been your biggest contribution to Thoughtbot?

### ISSUE THREAD

**Issue by alejorivera** [r00k/AMA#4]

**Comment by r00k** [comment]
Great question!

I have a hunch it's been my conference speaking. I meet a lot of people who told me they found Upcase or thoughtbot through a talk of mine.

Even more humbling, I've had folks tell me that a talk I gave changed their lives (!!!) by inspiring them to learn Ruby, or get serious about writing clean code, or leave their job for a better company.

A possible tie might be my hosting of the Giant Robots podcast.
