### ISSUE TITLE
Difficulty coming up with good design

### ISSUE THREAD

**Issue by DavsX** [r00k/AMA#40]
Hi!
Often I fail to come up with a reasonable abstraction, that would make sense, be pragmatic, simple and understandable by others (I try to not overengineer it).

Does this happen to you? What do you do in those situation? Do you think that it means, that the abstracting should not be done instead?

**Comment by r00k** [comment]
I fail to come up with great abstractions all the time. I think that's normal.

When I feel stuck, I like to ask a co-worker to swing by, or to open a pull and ask for ideas.
