### ISSUE TITLE
vim tabs/buffers/panes workflow

### ISSUE THREAD

**Issue by johnmosesman** [r00k/AMA#42]
Hi there,

I'm not sure I understand the workflow for vim tabs/buffers/panes. I'm coming from sublime where I would have a dual-split pane with multiple files open in each pane.

Am I trying to make vim behave like sublime or am I missing something? What do you recommend? (I'm also using tmux.)

John

**Comment by r00k** [comment]
I like a split with tests on the left and the code they test on the right.

I also tend to use tabs to hold pairs of test/code that are related.

But that's just my preference. You can do whatever lets you work quickly and efficiently.
