### ISSUE TITLE
Sublime To Vim

### ISSUE THREAD

**Issue by arbaaz** [r00k/AMA#45]
I have been using sublime text. I know basics of vim. How do I shift from sublime to vim. I find using vim very difficult and slow. Need to google everything for vim. How do I make this transition from sublime to vim.

**Comment by r00k** [comment]
http://www.benorenstein.com/blog/surviving-your-first-week-in-vim

**Comment by r00k** [comment]
By the way, a big part of this is just _sticking with it_. Yes it's hard at first. But so is anything worthwhile.

**Comment by arbaaz** [comment]
Thank you.

**Comment by calebeby** [comment]
The link doesn't work with the trailing slash.

**Comment by r00k** [comment]
Fixed. Thanks!
