### ISSUE TITLE
Vimperator

### ISSUE THREAD

**Issue by s3rvac** [r00k/AMA#46]
Hi Ben. Do you use a browser plugin such as [Vimperator](http://www.vimperator.org/vimperator) or [Vimium](https://vimium.github.io/)?

**Comment by r00k** [comment]
Yep. I use vimium.

Closes #46.

On Sunday, May 17, 2015, Petr Zemek notifications@github.com wrote:

> Hi Ben. Do you use a browser plugin such as Vimperator
> http://www.vimperator.org/vimperator or Vimium
> https://vimium.github.io/?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/r00k/AMA/issues/46.

## 

-Ben
