### ISSUE TITLE
Finding a job to grow as a developer

### ISSUE THREAD

**Issue by DavsX** [r00k/AMA#47]
Hi!
I think the key to become a good developer is to be around and work with good developers. As someone, who will be looking for a job soon (just finishing university, although I have some professional programming experience) I'd like to ask you about what to look for in job offers, how to spot good positions, where I could really learn (we are talking abount a job interview)? What to look for and what to avoid? (I'd like to avoid places, where they are just looking for code-monkeys)
Thanks.

**Comment by r00k** [comment]
Ask questions about how they plan to deal with the fact that you're new. Ask if you'll have a mentor.

Make friends who work in the industry. Ideally, have a friend that works at every place you apply to tell you if it's actually awesome or not. Ask lots of people which companies in your area are great.

Pay attention to where the people you admire work.
