### ISSUE TITLE
Thoughtbot AMA repo

### ISSUE THREAD

**Issue by cllns** [r00k/AMA#48]
Hey Ben!

How do you feel about making an AMA repo for thoughtbot? I have a question I'd like to ask y'all, not just you. (I could do it over email, or in this repo though, if you decide against it though)

You could link to it from the 'contact' link on your site, if you wanted: https://thoughtbot.com/locations

A possible name I just thought of is: `thoughtbot/ask-us-anything`.

**Comment by r00k** [comment]
Thanks for the idea, but I'm probably not going to create an AMA for thoughtbot. Maybe someone else is interested in doing so.

You can ask me something here if you like.
