### ISSUE TITLE
What are your thoughts on going API-first and using a front-end framework?

### ISSUE THREAD

**Issue by djpowers** [r00k/AMA#5]
It seems that there is a lot of talk about this process of app development, specifically versus a "traditional" Rails workflow. Do you see any advantages/drawbacks with this method?

**Comment by r00k** [comment]
I haven't done much of this personally, but I'll share a cherry-picked anecdote (not to be confused with a rigorous argument): a colleague recently wrote an app in Ember with a Rails backend (https://formkeep.com). I proposed a hypothetical world where he could snap his fingers and convert it into a pure Rails app instantly, for free. 

He said he'd do it.
