### ISSUE TITLE
Ruby 3.0 String immutable

### ISSUE THREAD

**Issue by itsyohan** [r00k/AMA#50]
**What are your thoughts on strings becoming immutable in the next major release of Ruby?**
And can you elaborate on the implications of this change, what issues there are with the current state of ruby that might have lead to this conclusion? 
[for reference](https://twitter.com/yukihiro_matz/status/634386185507311616)

**Comment by r00k** [comment]
> What are your thoughts on strings becoming immutable in the next major release of Ruby?

I'm excited! I'm very much in favor of immutable data in general.

> And can you elaborate on the implications of this change, what issues there are with the current state of ruby that might have lead to this conclusion? 

I could, but there have been lots of good things written about Clojure's choice to provide immutable data structures by default that will say it better. Should be easy to find.

**Comment by itsyohan** [comment]
Cool thanks!
