### ISSUE TITLE
Question about Investment Time

### ISSUE THREAD

**Issue by leenasn** [r00k/AMA#53]
Hi,

Your Playbook is really awesome, and the "Investment Time",  mentioned in your Playbook is really amazing and encouraging.

Had a question though. I believe its not always possible for everyone to be on "Investment Day" on every Fridays especially because you've mentioned if people are taking leave, or if there are other emergencies, Investment Time is skipped.

Would you be able to share the average percent in a month your team is using Investment Time? Is it like mostly 100% of people are able to utilise Investment Time most of the time or is it consistently like a certain percentage of does it vary hugely?

Thanks in advance.
Leena

**Comment by r00k** [comment]
Hi there!

I don't have numbers handy for this. It's possible @cpytel would.

**Comment by leenasn** [comment]
Thank you @r00k. Will wait to hear from @cpytel.

**Comment by cpytel** [comment]
We don't have any data on this, it's not something we generally track because it's mostly 100%.

Since we don't track it, when people do miss it we don't know why. For a few months we've been asking people who do miss it to register the reason. We're still collecting that data.

**Comment by leenasn** [comment]
Thank you @r00k and @cpytel for the response.
