### ISSUE TITLE
What is hardware and software you use?

### ISSUE THREAD

**Issue by mugukamil** [r00k/AMA#54]
What is hardware(monitor, keyboard, mouse, macbook pro? air? retina?). 
And favourite apps.

**Comment by r00k** [comment]
* 5K iMac at home
* 2019 15" MacBook Pro at work
* Kinesis Advantage keyboard
* Boring mouse
* Alfred
* Fantastical
* Dropbox (steadily getting worse 😢 )
* Superhuman
* Discord
* Telegram
* Reflect.
