### ISSUE TITLE
Learning Ruby and Ruby on Rails

### ISSUE THREAD

**Issue by nicholastillman** [r00k/AMA#55]
I'm new to Ruby and have been chugging through Learn Ruby the Hard Way. Some of it is starting to click yet some, I'm just plain lost, in the sense, will I retain what I just typed? Anywho, wanted to know how you got started in Ruby Programming and if you have any tips on learning as a beginner.

Thanks for your time.
- Nicholas

**Comment by r00k** [comment]
Getting started is the hardest part. It'll get easier if you stick with it. Don't doubt yourself; this stuff is just hard.

Learning on your own makes things harder. Here's how you can learn with others:

Two recommendations:
1. Ideally, go do the program at Turing: http://turing.io.
2. If you can't go to an in-person school, check out https://launchschool.com/.
