### ISSUE TITLE
How to make public speaking more entertaining

### ISSUE THREAD

**Issue by samselikoff** [r00k/AMA#6]
Could you give some tips on how to give talks that are entertaining? Public speaker doesn't really terrify me, but I find it hard to work in humor, storytelling, etc. into my talks.

Thanks for your thoughts!

**Comment by r00k** [comment]
- Do something that catches attention in the first 60 seconds.
- Change topics every 10 minutes at most.
- Prefer live demos to slides. Show, don't tell.
- If you do use slides, make them interesting. For god's sake don't read them.
- Encourage audience participation. Even doing "raise your hand if..." polls will wake people up.
- Vary your tone of voice, pace, body language, and where you stand. (I like to hop off the stage and stroll the aisles. Or stand very still when making an important point.)
- Get to the point and stay there.

**Comment by mxgrn** [comment]
@samselikoff Just watched Ben's talk on this, it's both informative _and_ a great example of how to give talks: https://www.youtube.com/watch?v=l9JXH7JPjR4

**Comment by samselikoff** [comment]
@mxgrn awesome, thanks a lot!
